/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package opac;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shanthini
 */
public class opac extends javax.swing.JFrame {

    /**
     * Creates new form opac
     */
    Connection con;
    public opac() {
        try {
            initComponents();
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/libdatabase","root","july");
            System.out.println("Connection established");
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        memName = new javax.swing.JTextField();
        memId = new javax.swing.JTextField();
        memYear = new javax.swing.JTextField();
        memDept = new javax.swing.JTextField();
        memIssued = new javax.swing.JTextField();
        memCat = new javax.swing.JComboBox();
        memSubmit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        accessNo = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        status = new javax.swing.JComboBox();
        bookSubmit = new javax.swing.JButton();
        container2 = new javax.swing.JPanel();
        searchTitle = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bookTitle = new javax.swing.JTextField();
        tSearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchAuthor = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bookAuthor = new javax.swing.JTextField();
        aSearch = new javax.swing.JButton();
        issuePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        issueCat = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        bookToIssue = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        memberId = new javax.swing.JTextField();
        issueButton = new javax.swing.JButton();
        returnPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        retMember = new javax.swing.JTextField();
        retBook = new javax.swing.JTextField();
        returnButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        retAccess = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        issueMem = new javax.swing.JTextField();
        listButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("member id:");

        jLabel3.setText("category");

        jLabel4.setText("dept:");

        jLabel5.setText("year:");

        jLabel6.setText("issue count:");

        memCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "student", "staff" }));
        memCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memCatActionPerformed(evt);
            }
        });

        memSubmit.setText("Submit");
        memSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memIssued, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(memCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(memName)
                                .addComponent(memId)
                                .addComponent(memDept)
                                .addComponent(memYear))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(memSubmit)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(memName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(memId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(memCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(memDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(memYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(memIssued, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(memSubmit)
                .addContainerGap())
        );

        l1.setText("Title:");

        l2.setText("Access no:");

        l3.setText("category:");

        l4.setText("author:");

        l5.setText("status:");

        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "available", "issued", "transferred" }));

        bookSubmit.setText("Submit");
        bookSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1)
                            .addComponent(l2)
                            .addComponent(l3)
                            .addComponent(l4)
                            .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(accessNo)
                            .addComponent(category)
                            .addComponent(author)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(bookSubmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l2)
                    .addComponent(accessNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l4)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l5)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bookSubmit))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Entry", jPanel2);

        jLabel7.setText("Book title:");

        tSearch.setText("Search");
        tSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSearchActionPerformed(evt);
            }
        });

        jLabel8.setText("Search by title");

        javax.swing.GroupLayout searchTitleLayout = new javax.swing.GroupLayout(searchTitle);
        searchTitle.setLayout(searchTitleLayout);
        searchTitleLayout.setHorizontalGroup(
            searchTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTitleLayout.createSequentialGroup()
                .addGroup(searchTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTitleLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(tSearch))
                    .addGroup(searchTitleLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(searchTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(searchTitleLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchTitleLayout.setVerticalGroup(
            searchTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTitleLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tSearch)
                .addContainerGap())
        );

        jLabel9.setText("Search by author");

        jLabel10.setText("Author:");

        aSearch.setText("Search");
        aSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchAuthorLayout = new javax.swing.GroupLayout(searchAuthor);
        searchAuthor.setLayout(searchAuthorLayout);
        searchAuthorLayout.setHorizontalGroup(
            searchAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAuthorLayout.createSequentialGroup()
                .addGroup(searchAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchAuthorLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(aSearch))
                    .addGroup(searchAuthorLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(searchAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(searchAuthorLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchAuthorLayout.setVerticalGroup(
            searchAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAuthorLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aSearch)
                .addContainerGap())
        );

        javax.swing.GroupLayout container2Layout = new javax.swing.GroupLayout(container2);
        container2.setLayout(container2Layout);
        container2Layout.setHorizontalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(searchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        container2Layout.setVerticalGroup(
            container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(container2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", container2);

        jLabel11.setText("Category:");

        issueCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "staff", "student" }));

        jLabel12.setText("Book:");

        jLabel13.setText("Member id:");

        issueButton.setText("Issue");
        issueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout issuePanelLayout = new javax.swing.GroupLayout(issuePanel);
        issuePanel.setLayout(issuePanelLayout);
        issuePanelLayout.setHorizontalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(issuePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(issueCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookToIssue)
                            .addComponent(memberId)))
                    .addGroup(issuePanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(issueButton)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        issuePanelLayout.setVerticalGroup(
            issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issuePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(issueCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bookToIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(issuePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(memberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issueButton)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Issue", issuePanel);

        jLabel14.setText("Member id:");

        jLabel15.setText("Book name:");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Access no:");

        javax.swing.GroupLayout returnPanelLayout = new javax.swing.GroupLayout(returnPanel);
        returnPanel.setLayout(returnPanelLayout);
        returnPanelLayout.setHorizontalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(retMember, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 357, Short.MAX_VALUE))
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(returnPanelLayout.createSequentialGroup()
                                        .addComponent(retAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(retBook)))))
                    .addGroup(returnPanelLayout.createSequentialGroup()
                        .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(returnButton))
                            .addGroup(returnPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        returnPanelLayout.setVerticalGroup(
            returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(retMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(retBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(retAccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(returnButton)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Return", returnPanel);

        jLabel17.setText("Member id:");

        listButton.setText("list");
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issueMem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(issueMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List issue details", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSubmitActionPerformed
        try {
            // TODO add your handling code here:
            String t=title.getText();
            //JOptionPane.showMessageDialog(null,t);
            String ano=accessNo.getText();
            String cat=category.getText();
            String auth=author.getText();
            String stat=(String)status.getSelectedItem();
            //JOptionPane.showMessageDialog(null,stat);
            PreparedStatement ps=con.prepareStatement("insert into bookdetails values(?,?,?,?,?)");
            ps.setString(1,t);
            ps.setString(2,ano);
            ps.setString(3,auth);
            ps.setString(4,cat);
            ps.setString(5,stat);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Book entered successfully!");
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_bookSubmitActionPerformed

    private void memCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memCatActionPerformed

    private void memSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memSubmitActionPerformed
        try {
            // TODO add your handling code here:
            String n=memName.getText();
            //JOptionPane.showMessageDialog(null,t);
            String id=memId.getText();
            String cat=(String)memCat.getSelectedItem();
            String dept=memDept.getText();
            String yr=memYear.getText();
            String issue=memIssued.getText();
            int cnt=Integer.parseInt(issue);
                //JOptionPane.showMessageDialog(null,stat);
            PreparedStatement ps=con.prepareStatement("insert into memberdetails values(?,?,?,?,?,?)");
            ps.setString(1,n);
            ps.setString(2,id);
            ps.setString(3,cat);
            ps.setString(4,dept);
            ps.setString(5,yr);
            ps.setInt(6,cnt);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Member entered successfully!");
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_memSubmitActionPerformed

    private void tSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSearchActionPerformed
        try {
            // TODO add your handling code here:
            String t=bookTitle.getText();
            String s;
            //JOptionPane.showMessageDialog(null,t);
            PreparedStatement ps=con.prepareStatement("select * from bookdetails where title=?");
            ps.setString(1,t);
            ps.executeQuery();
            ResultSet rs=ps.getResultSet();
            if(!ps.execute())
                JOptionPane.showMessageDialog(null,"Book doesn't exist");
            else
            {
            while(rs.next())
            {
                if(rs.getString(5).equals("issued"))
                {
                    PreparedStatement ps1=con.prepareStatement("select memberId from issuedetails where accessNo=?");
                    ps1.setString(1,rs.getString(2));
                    ps1.executeQuery();
                    ResultSet rs2=ps1.getResultSet();
                    s="Book details\nTitle:"+rs.getString(1)+"\nAccess no:"+rs.getString(2)+"\nAuthor:"+rs.getString(3)+"\nCategory:"+rs.getString(4)+"\nStatus:"+rs.getString(5);
                    while(rs2.next())
                    {
                       s=s+rs2.getString(1);
                        JOptionPane.showMessageDialog(null,s);
                    }
                }
                else
                {
                s="Book details\nTitle:"+rs.getString(1)+"\nAccess no:"+rs.getString(2)+"\nAuthor:"+rs.getString(3)+"\nCategory:"+rs.getString(4)+"\nStatus:"+rs.getString(5);
                JOptionPane.showMessageDialog(null,s);
                }
            }
            }
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tSearchActionPerformed

    private void aSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSearchActionPerformed
        try {
            // TODO add your handling code here:
                String a=bookAuthor.getText();
                String s;
                //JOptionPane.showMessageDialog(null,t);
                PreparedStatement ps=con.prepareStatement("select * from bookdetails where author=?");
                ps.setString(1,a);
                JOptionPane.showMessageDialog(null,a);
                ps.executeQuery();
                ResultSet rs=ps.getResultSet();
                if(!ps.execute())
                    JOptionPane.showMessageDialog(null,"Book doesn't exist");
                else
                {
                while(rs.next())
                {
                    //JOptionPane.showMessageDialog(null,"Entered");
                    if(rs.getString(5).equals("issued"))
                    {
                        //JOptionPane.showMessageDialog(null,"Entered");
                        PreparedStatement ps1=con.prepareStatement("select memberId from issuedetails where accessNo=?");
                        ps1.setString(1,rs.getString(2));
                        ps1.executeQuery();
                        ResultSet rs2=ps1.getResultSet();
                        s="Book details\nTitle:"+rs.getString(1)+"\nAccess no:"+rs.getString(2)+"\nAuthor:"+rs.getString(3)+"\nCategory:"+rs.getString(4)+"\nStatus:"+rs.getString(5);
                        while(rs2.next())
                        {
                           s=s+rs2.getString(1);
                            JOptionPane.showMessageDialog(null,s);
                        }
                    }
                    else
                    {
                  //  JOptionPane.showMessageDialog(null,"Entered");
                    s="Book details\nTitle:"+rs.getString(1)+"\nAccess no:"+rs.getString(2)+"\nAuthor:"+rs.getString(3)+"\nCategory:"+rs.getString(4)+"\nStatus:"+rs.getString(5);
                    JOptionPane.showMessageDialog(null,s);
                    }
                }
                }
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aSearchActionPerformed

    private void issueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueButtonActionPerformed
        try {
            // TODO add your handling code here:
                String id=memberId.getText();
                String book=bookToIssue.getText();
                String cat=(String)issueCat.getSelectedItem();
                Date date1=new Date();
                int flag=0;
                SimpleDateFormat df1=new SimpleDateFormat("dd");
                SimpleDateFormat df2=new SimpleDateFormat("MM");
                SimpleDateFormat df3=new SimpleDateFormat("yyyy");
                int d=Integer.parseInt(df1.format(date1));
                int mon=Integer.parseInt(df2.format(date1));
                int yr=Integer.parseInt(df3.format(date1));
                mon=mon+6;
                if(mon>12)
                {
                    yr++;
                    mon=mon-12;
                }
                String m=Integer.toString(mon);
                String y=Integer.toString(yr);
                String dt2=df1.format(date1)+"-"+m+"-"+y;
                //System.out.println(m);
                String dt=df1.format(date1)+"-"+df2.format(date1)+"-"+df3.format(date1);
                //JOptionPane.showMessageDialog(null,df1.format(date1));
                PreparedStatement ps=con.prepareStatement("select * from bookdetails where title=?");
                ps.setString(1,book);
                ps.executeQuery();
                ResultSet rs=ps.getResultSet();
                while(rs.next())
                {
                    if(rs.getString(5).equals("available")&& flag==0)
                    {
                        PreparedStatement ps2=con.prepareStatement("select * from memberdetails where memberId=?");
                        ps2.setString(1,id);
                        ps2.executeQuery();
                        ResultSet rs2=ps2.getResultSet();
                        while(rs2.next())
                        {
                            if((rs2.getString(3).equals("staff") && rs2.getInt(6)<5) ||(rs2.getString(3).equals("student") && rs2.getInt(6)<3))
                            {
                                System.out.println("issued");
                                    PreparedStatement ps1=con.prepareStatement("insert into issuedetails values(?,?,?,?,?)");
                                    ps1.setString(1,rs.getString(2));
                                    ps1.setString(2,id);
                                    ps1.setString(3,dt);
                                    ps1.setString(4,dt2);
                                    ps1.setInt(5,0);
                                    ps1.executeUpdate();
                                    flag=1;
                                    PreparedStatement ps4=con.prepareStatement("update memberdetails set issueCount=? where memberId=?");
                                    ps4.setInt(1,rs2.getInt(6)+1);
                                    ps4.setString(2,id);
                                    ps4.executeUpdate();
                                    PreparedStatement ps3=con.prepareStatement("update bookdetails set status=? where accessNo=?");
                                    ps3.setString(1,"issued");
                                    ps3.setString(2,rs.getString(2));
                                    ps3.executeUpdate();
                                    JOptionPane.showMessageDialog(null,"issued");
                            }
                            else
                                JOptionPane.showMessageDialog(null,"Issue count exceeded");
                        }
                    }
                }
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_issueButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        try {
            // TODO add your handling code here:
                
            String id=retMember.getText();
            String book=retBook.getText();
            String ano=retAccess.getText();
            Date date1=new Date();
            int flag=0,f;
            SimpleDateFormat df1=new SimpleDateFormat("dd");
            SimpleDateFormat df2=new SimpleDateFormat("MM");
            SimpleDateFormat df3=new SimpleDateFormat("yyyy");
            int d=Integer.parseInt(df1.format(date1));
            int mon=Integer.parseInt(df2.format(date1));
            int yr=Integer.parseInt(df3.format(date1));
            String dt2;
            int rd,rmon,ryr;
            //System.out.println(m);
            String dt=df1.format(date1)+"-"+df2.format(date1)+"-"+df3.format(date1);
            //JOptionPane.showMessageDialog(null,df1.format(date1));
            PreparedStatement ps=con.prepareStatement("select * from issuedetails where accessNo=?");
            ps.setString(1,ano);
            ps.executeQuery();
            String[] retDate;
            ResultSet rs=ps.getResultSet();
            String fine;
            int cnt;
            while(rs.next())
            {
                
                dt2=rs.getString(4);
                retDate=dt2.split("-");
                rd=Integer.parseInt(retDate[0]);
                rmon=Integer.parseInt(retDate[1]);
                ryr=Integer.parseInt(retDate[2]);
                //rd=24;rmon=9;ryr=2013;
                if(yr>ryr ||(yr==ryr && mon>rmon)||(yr==ryr && mon==rmon && d>rd))
                {
                    f=yr-ryr;
                    f*=365;
                    f=f+((mon-rmon)*30)+(d-rd);f=f*2;
                    fine="Pay fine of : Rs."+Integer.toString(f);
                    JOptionPane.showMessageDialog(null,fine);
                    PreparedStatement ps1=con.prepareStatement("delete from issuedetails where accessNo=?");
                    ps1.setString(1,ano);
                    ps1.executeUpdate();
                }
                PreparedStatement ps3=con.prepareStatement("select * from memberdetails where memberId=?");
                ps3.setString(1,id);
                ps3.executeQuery();
                ResultSet rs3=ps3.getResultSet();
                while(rs3.next())
                {
                    cnt=rs3.getInt(6);
                    PreparedStatement ps2=con.prepareStatement("update memberdetails set issuecount=? where memberId=?");
                    ps2.setInt(1,cnt-1);
                    ps2.setString(2,id);
                }
                PreparedStatement ps4=con.prepareStatement("update bookdetails set status=? where accessNo=?");
                ps4.setString(1,"available");
                ps4.setString(2,ano);
                ps4.executeUpdate();
                JOptionPane.showMessageDialog(null,"Returned!");
              }

        } catch (SQLException ex) {      
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_returnButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        try {
            // TODO add your handling code here:
            String id=issueMem.getText();
            PreparedStatement ps=con.prepareStatement("select * from issuedetails where memberId=?");
            ps.setString(1,id);
            ps.executeQuery();
            String s;
            ResultSet rs=ps.getResultSet();
            while(rs.next())
            {
                PreparedStatement ps1=con.prepareStatement("select * from bookdetails where accessNo=?");
                ps1.setString(1,rs.getString(1));
                ps1.executeQuery();
                ResultSet rs2=ps1.getResultSet();
                while(rs2.next())
                {
                    s="Details:\nBook:"+rs2.getString(1)+"\nMember id:"+rs.getString(2);
                    JOptionPane.showMessageDialog(null,s);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(opac.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opac().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aSearch;
    private javax.swing.JTextField accessNo;
    private javax.swing.JTextField author;
    private javax.swing.JTextField bookAuthor;
    private javax.swing.JButton bookSubmit;
    private javax.swing.JTextField bookTitle;
    private javax.swing.JTextField bookToIssue;
    private javax.swing.JTextField category;
    private javax.swing.JPanel container2;
    private javax.swing.JButton issueButton;
    private javax.swing.JComboBox issueCat;
    private javax.swing.JTextField issueMem;
    private javax.swing.JPanel issuePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JButton listButton;
    private javax.swing.JComboBox memCat;
    private javax.swing.JTextField memDept;
    private javax.swing.JTextField memId;
    private javax.swing.JTextField memIssued;
    private javax.swing.JTextField memName;
    private javax.swing.JButton memSubmit;
    private javax.swing.JTextField memYear;
    private javax.swing.JTextField memberId;
    private javax.swing.JTextField retAccess;
    private javax.swing.JTextField retBook;
    private javax.swing.JTextField retMember;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel returnPanel;
    private javax.swing.JPanel searchAuthor;
    private javax.swing.JPanel searchTitle;
    private javax.swing.JComboBox status;
    private javax.swing.JButton tSearch;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
